name: Release

on:
  push:
    tags:
      - v*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ReleaseJar:
    name: Make a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew fatJar

      - uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'push' }}
        with:
          artifacts: "build/libs/*.jar"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}